### ISSUE TITLE
Solve the problems with the NER feature

### ISSUE THREAD

**Issue by CATS-Project** [CATS-Project/CATS#9]
The NER feature seems buggy when no filter is applied. When sampled, it seems to be much more accurate.

**Comment by cipriantruica** [comment]
I don't know why this happens, probably is because of the nltk name-entities package.

**Comment by AdrienGuille** [comment]
In my opinion the explanation for this is two fold:
(i) The model in this package was apparently trained on news articles. However, tweets - mostly because of the 140 character limit - are written with a very particular style in comparison with news articles. Therefore, one way to improve performance would be to annotate some tweets and train the model with it.
(ii) When you filter tweets according to a keyword, e.g. London, you'll get a set of coherent tweets, in the sense that they're all discussing something related to the city of London. Because the detected named-entities are sorted according to their frequency, the most common NE will be places in London. But if you look at the named-entities detected in a very heterogeneous set of tweets (in terms of topics) then the most frequent named-entities are very common words that the model tends to detect as named-entities, whatever the context. So basically, to obtain interesting named-entities, one should focus on a specific set of tweets revolving around a specific topic.

**Comment by cipriantruica** [comment]
I think, but I'm not sure, that we can train a model using our own corpus that can be used by NLTK. Probably, we should look into this. The default corpus used for the named entities I think is the CONLL 2002 Named Entity Recognition Corpus. The complete list of corpora used  by the NLTK can be found here http://www.nltk.org/nltk_data/.

**Comment by AdrienGuille** [comment]
After looking at your code, it appears that you're using the NTLK Named Entity Chunker, which is not trained with the "CONLL 2002 Named Entity Recognition" corpus (which only cover Dutch and Spanish, not English by the way). The model you're using was trained with the ACE data: 
https://catalog.ldc.upenn.edu/LDC2005T09
Here's a page that describes how the training data should be formatted:
http://www.succeed-project.eu/wiki/index.php/NLTK#Input_format_for_training
This page provides interesting information about the way the chunker works:
http://mattshomepage.com/#/blog/feb2013/liftingthehood
